apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  replicas: 0
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: wesleywillians/goserver
        ports:
        - containerPort: 9090